### ISSUE TITLE
fix various deprecation warnings

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#67]
A couple I'm seeing right now:

```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

password { "password_is_12345" }

To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:

rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct

 (called from block (2 levels) in <top (required)> at /home/ubuntu/newspaper_works/spec/factories/user.rb:5)
```

and

```
DEPRECATION WARNING: human_readable_type= is deprecated and will be removed from a future release (human_readable_type is deprecated. Set the i18n key for activefedora.models.#{model_name.i18n_key} instead. This will be removed in Hyrax 3). (called from <class:NewspaperTitle> at /home/ubuntu/newspaper_works/app/models/newspaper_title.rb:46) (1 times); e.g.: 
    /home/ubuntu/newspaper_works/app/models/newspaper_title.rb:46:in `<class:NewspaperTitle>'
    /home/ubuntu/newspaper_works/app/models/newspaper_title.rb:2:in `<top (required)>'
    /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
    /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
    /var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
```

Add more as comments on this issue as they pop up.

**Comment by ebenenglish** [comment]
Fixed via #127
